#!/bin/sh
PATH="/home/user/Desktop/musl-cross/riscv32-linux-musl-cross/bin/:$PATH"
riscv32-linux-musl-as revshell.s -o revshell.o && \
riscv32-linux-musl-ld -O0 revshell.o -o revshell --nostdlib --static && \
riscv32-linux-musl-objdump -d revshell

