#!/bin/sh
PATH="/home/user/Desktop/musl-cross/riscv32-linux-musl-cross/bin/:$PATH"
riscv32-linux-musl-as bind.s -o bind.o && \
riscv32-linux-musl-ld -O0 bind.o -o bind --nostdlib --static && \
riscv32-linux-musl-objdump -d bind

